language: android
sudo: false
android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt_packages:
    - pandoc
before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
install:
  - curl -O https://developers.google.com/games/services/downloads/gpg-cpp-sdk.v1.4.1.zip
  - (cd hello-thirdparty && unzip ../gpg-cpp-sdk.v1.4.1.zip)
script:
  - (cd builder && ./gradlew test)
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
  - for f in */README.md; do sed -n '/Support/,/License/p' $f > /tmp/$(dirname $f).readme; done && diff -u --from-file=/tmp/hello-jni.readme /tmp/*.readme
  - test "$(grep -H compileSdkVersion */app/build.gradle | tee /dev/stderr | cut -d= -f 2 | sort | uniq | wc -l)" = "1"
  - test "$(grep -H targetSdkVersion */app/build.gradle | tee /dev/stderr | cut -d= -f 2 | sort | uniq | wc -l)" = "1"
  - test "$(grep -H buildToolsVersion */app/build.gradle | tee /dev/stderr | cut -d= -f 2 | sort | uniq | wc -l)" = "1"
